### ISSUE TITLE
Report Content Blocking prefs and exception status in the payload

### ISSUE THREAD

**Issue by johannhof** [mozilla/FastBlockShield#69]
We should report the state of the following prefs in the payload:

- `browser.contentblocking.enabled`
- `browser.fastblock.enabled`
- `privacy.trackingprotection.enabled`
- `privacy.trackingprotection.pbmode.enabled`

To ensure that we cover users that decide to turn off content blocking.

We should also report whether the user has added an exception for the site, I suppose. Adding an exception will reload the page.

**Comment by ericawright** [comment]
Can Normandy take care of removing users who change certain prefs @mythmon?

**Comment by mythmon** [comment]
@ericawright if those preferences are part of the original targeting criteria, then yes. When those criteria no longer match, Normandy will unenroll the user.

**Comment by ericawright** [comment]
@mythmon great! any chance it can do the same for installing addons that were filtered out in the targeting criteria?

**Comment by mythmon** [comment]
Any targeting criteria that becomes invalid will cause the study to be removed the next time Normandy checks in. It won't be instant, but it should be quick enough for most purposes (usually within one session).

**Comment by ericawright** [comment]
@johannhof with Normandy being able to kick users for these changes, do you still think it is worth reporting this info in the payload?

**Comment by johannhof** [comment]
Yes, I think we still want this, since this is the only way we can tell e.g. whether "TP" users turned off tracking protection in the midst of the study, right?

**Comment by ericawright** [comment]
@johannhof I see, that would be a pref which was part of the targeting criteria then changes, but not to a state that disqualifies them.
@mythmon - just to clarify, if our study changes a pref - that was part of targeting criteria - into a state that would disqualify the user will that unenroll them, or only if it is changed by the user?

**Comment by johannhof** [comment]
Yes, so, another reason I don't want to filter on these prefs too much via Normandy is that they are easily changed by the user, e.g. browser.contentblocking.enabled is very prominently exposed via a simple switch in the hamburger menu. Since this UI is new I expect a bunch of users to try it out, and I want to avoid disqualifying them all only because they had a single pref wrong for a little bit (in this example they won't send any telemetry anyway since they don't detect trackers anymore).

**Comment by mythmon** [comment]
> @mythmon - just to clarify, if our study changes a pref - that was part of targeting criteria - into a state that would disqualify the user will that unenroll them, or only if it is changed by the user?

Unfortunately, it can't be determined *who* changed a preference. To Normandy, any change acts the same.

It is technically possible to make a recipe that enrolls in certain situations and then stays enrolled in other situations. This is done by making one of the criteria something like `prefIsSet || addonIsInstalled`. That would cause the user to stay enrolled. It's also possible to do even more complex things in the filter expressions. I would recommend not doing this though.

I think @johannhof's idea is a good one. Preferences that are expected to change during the lifetime of the study probably should not be part of the targeting criteria, mostly because once a user unenrolls they can't be re-enrolled. If that filtering is done in the add-on, then it won't cause spurious permanent unenrollment.

However, please make sure in your telemetry to note when users have the add-on installed but disabled. That will make things easier later.
